# Generated by Django 6.1 on 2026-08-10 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROVIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
