# Generated by Django 6.1 on 2026-08-12 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('provider', 'booking_date', 'booking_time'), name='unique_active_provider_booking'),
        ),
    ]
